/*
=> create comments feature
=> create interactions feature
=> create content Reports feature
=> favorite feature
=> following/follower feature

-----------------------------------------------------------------------------------
=> swagger integration for all routes
=> DI(Dependency Injection) for features  with refactoring any necessary code.
=> testing the project (unite tests , integration tests, E2E tests)S
=> thinking of adding notifications with sockits to the project

-------------------------------------------------------------------------------------
 !!Ideas that may be added to the project 
 => auto localization with using ai
 => content enhancement suggestion from AI based models
 =>blogs some metadata generated by ai models automatically
 => prime membership feature (with different subscriptions models)
 => content moderation feature
*/
